# Generated by Django 4.1.5 on 2023-04-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='price',
            field=models.CharField(max_length=150),
        ),
    ]
