# Generated by Django 4.2.4 on 2023-08-11 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_testimony_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='image',
            new_name='image1',
        ),
    ]
